#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1.3 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Feb 02 11:40:05 CET 2022
# SW Build 2644227 on Wed Sep  4 09:44:18 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim controller_tb_behav -key {Behavioral:sim_1:Functional:controller_tb} -tclbatch controller_tb.tcl -log simulate.log"
xsim controller_tb_behav -key {Behavioral:sim_1:Functional:controller_tb} -tclbatch controller_tb.tcl -log simulate.log

